# name: Deploy to GCP

# on:
#   push:
#     branches:
#       - main

# permissions:
#   id-token: write
#   contents: read

# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     env:
#       PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}

#     steps:
#       - name: Checkout
#         uses: actions/checkout@v4

#       - name: Authenticate to GCP (WIF)
#         uses: google-github-actions/auth@v2
#         with:
#           workload_identity_provider: "${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}"
#           service_account: "${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }}"

#       - name: Setup gcloud
#         uses: google-github-actions/setup-gcloud@v2

#       - name: Verify Auth
#         run: gcloud auth list

#       - name: Deploy Cloud Run
#         run: |
#           gcloud run deploy my-service \
#             --image gcr.io/$PROJECT_ID/my-image \
#             --region asia-south1 \
#             --platform managed \
#             --allow-unauthenticated